const taskMap={"聊天":"聊天 / 综合","学习":"学习 / 研究","写作":"聊天 / 综合","图片":"图片","视频":"视频","编程":"编程"};

const tools=[
["ChatGPT","💬","聊天 / 综合","通用 AI 助手，可聊天、搜索、分析文件与生成图片。","免费入口","https://chatgpt.com/","OpenAI"],
["Gemini","✨","聊天 / 综合","Google 的多模态 AI 助手，适合搜索、写作与图片理解。","免费入口","https://gemini.google.com/","Google"],
["Claude","🧠","聊天 / 综合","长文本、写作、分析和编程都很强的通用助手。","免费入口","https://claude.ai/","Anthropic"],
["Perplexity","🔎","搜索 / 研究","AI 搜索与研究工具，适合快速找资料和来源。","免费入口","https://www.perplexity.ai/","Perplexity"],
["NotebookLM","📚","学习 / 研究","把自己的资料交给 AI 做总结、问答和研究。","免费入口","https://notebooklm.google.com/","Google"],
["Microsoft Copilot","🪟","聊天 / 办公","微软 AI 助手，提供免费聊天与生产力功能。","免费入口","https://copilot.microsoft.com/","Microsoft"],
["GitHub Copilot","⌨️","编程","AI 编程助手，Free 计划提供有限额度。","免费额度","https://github.com/features/copilot","GitHub"],
["Gemini Code Assist","👨‍💻","编程","Google 的 AI 编程助手，适合 IDE 开发与代码辅助。","免费入口","https://developers.google.com/gemini-code-assist","Google"],
["Cursor","⚡","编程","AI-first 代码编辑器，提供免费使用额度。","免费额度","https://cursor.com/","Cursor"],
["Hugging Face","🤗","模型 / 开源","开源模型、数据集、Spaces 与 AI 社区的大仓库。","免费 / 开源","https://huggingface.co/","Hugging Face"],
["Ollama","🦙","本地 AI","本地运行开源大模型，适合不想把数据交出去的人。","免费 / 开源","https://ollama.com/","Ollama"],
["LM Studio","🖥️","本地 AI","桌面端本地运行和管理大模型。","免费 / 本地","https://lmstudio.ai/","LM Studio"],
["Leonardo AI","🎨","图片","AI 图片生成与创作工具，有免费额度。","免费额度","https://leonardo.ai/","Leonardo"],
["Ideogram","🖼️","图片","擅长海报、文字排版和创意图像生成。","免费额度","https://ideogram.ai/","Ideogram"],
["Adobe Firefly","🔥","图片 / 设计","Adobe 的生成式 AI 工具，提供免费生成额度。","免费额度","https://firefly.adobe.com/","Adobe"],
["Canva","🪄","设计 / 图片","在线设计平台，集成多种 AI 创作功能。","免费入口","https://www.canva.com/ai/","Canva"],
["Microsoft Designer","🎨","设计","用 AI 快速制作图片、海报和社交媒体素材。","免费入口","https://designer.microsoft.com/","Microsoft"],
["PhotoRoom","📸","图片 / 抠图","AI 商品图、背景移除和图片处理。","免费入口","https://www.photoroom.com/","PhotoRoom"],
["CapCut","✂️","视频","AI 视频生成、剪辑、字幕和创作工具。","免费入口","https://www.capcut.com/","CapCut"],
["Pika","🎬","视频","短视频生成与创意特效工具，提供免费入口。","免费额度","https://pika.art/","Pika"],
["Runway","🎞️","视频","专业生成式视频工作流，提供免费试用额度。","免费试用","https://runwayml.com/","Runway"],
["Kling AI","🚀","视频","文本/图片生成视频与运动控制工具。","免费额度","https://klingai.com/","Kuaishou"],
["Luma Dream Machine","🌌","视频","偏电影感的视频生成与图像动画工具。","免费入口","https://lumalabs.ai/dream-machine","Luma"],
["Hailuo AI","🎥","视频","AI 视频生成工具，适合短视频与视觉实验。","免费入口","https://hailuoai.video/","MiniMax"],
["ElevenLabs","🎙️","音频 / 配音","AI 语音、配音和音频生成平台。","免费额度","https://elevenlabs.io/","ElevenLabs"],
["Suno","🎵","音乐","用文字生成歌曲和音乐作品。","免费额度","https://suno.com/","Suno"],
["Udio","🎶","音乐","AI 音乐生成与歌曲创作平台。","免费额度","https://udio.com/","Udio"],
["Gamma","📊","演示 / 文档","AI 生成演示文稿、文档和网页。","免费入口","https://gamma.app/","Gamma"],
["Napkin AI","📝","图表 / 文档","把文字内容快速转换成图表和视觉表达。","免费入口","https://www.napkin.ai/","Napkin"],
["Descript","🎤","视频 / 音频","文字驱动的视频和播客编辑工具，含 AI 功能。","免费入口","https://www.descript.com/","Descript"],
["DeepSeek","🐋","聊天 / 综合","国产通用 AI 助手，适合问答、推理、写作与代码。","免费使用","https://chat.deepseek.com/","DeepSeek"],
["豆包","🥔","聊天 / 综合","字节跳动 AI 助手，支持聊天、写作、图片、语音等。","免费使用","https://www.doubao.com/","字节跳动"],
["Kimi","🌙","聊天 / 综合","长文档、研究、写作与复杂任务助手。","免费使用","https://www.kimi.com/","Moonshot AI"],
["通义千问","🧠","聊天 / 综合","阿里通义 AI 助手，覆盖问答、写作、学习与多模态。","免费使用","https://www.qianwen.com/","Alibaba"],
["文心助手","🧭","聊天 / 综合","百度 AI 助手，提供问答、写作、搜索与办公能力。","免费使用","https://yiyan.baidu.com/","Baidu"],
["腾讯元宝","🪙","聊天 / 综合","腾讯 AI 助手，适合日常问答、文件处理与内容创作。","免费使用","https://yuanbao.tencent.com/","Tencent"],
["智谱清言","🟣","聊天 / 综合","智谱 AI 对话助手，支持写作、学习和代码等任务。","免费入口","https://chatglm.cn/","Zhipu AI"],
["秘塔AI搜索","🔍","搜索 / 研究","中文 AI 搜索与研究工具，适合查资料和整理信息。","免费使用","https://metaso.cn/","Metaso"],
["Poe","🧩","聊天 / 综合","多模型 AI 聊天平台，可体验不同模型与机器人。","免费额度","https://poe.com/","Quora"],
["HuggingChat","🤗","模型 / 开源","Hugging Face 的开放式 AI 聊天入口，可体验开源模型。","免费使用","https://huggingface.co/chat/","Hugging Face"],
["Mistral Le Chat","🌬️","聊天 / 综合","Mistral 的多功能 AI 助手，支持写作、研究和代码。","免费入口","https://chat.mistral.ai/","Mistral AI"],
["Google AI Studio","🧪","开发 / 模型","直接体验 Gemini 模型并制作 AI 原型。","免费额度","https://aistudio.google.com/","Google"],
["Groq","⚡","开发 / 模型","高速运行多种开源模型的 AI 平台。","免费额度","https://groq.com/","Groq"],
["Grammarly","✏️","写作 / 办公","英文语法、润色、改写和写作辅助工具。","免费入口","https://www.grammarly.com/","Grammarly"],
["QuillBot","🪶","写作 / 办公","英文改写、总结、语法检查和翻译工具。","免费入口","https://quillbot.com/","QuillBot"],
["DeepL","🌐","翻译","高质量文本与文档翻译工具。","免费入口","https://www.deepl.com/","DeepL"],
["Google Translate","🗺️","翻译","支持文字、图片、语音和网页翻译。","免费使用","https://translate.google.com/","Google"],
["Jimeng AI","🎨","图片","字节跳动即梦 AI，适合图片创作与视觉设计。","免费额度","https://jimeng.jianying.com/","ByteDance"],
["SeaArt AI","🖌️","图片","AI 绘画与模型社区，提供大量创作模型。","免费额度","https://www.seaart.ai/","SeaArt"],
["Tensor.Art","🧰","图片","在线 AI 绘画与模型工作台，支持多种开源模型。","免费额度","https://tensor.art/","Tensor.Art"],
["Mage.space","🧙","图片","在线 AI 图像生成平台，提供免费体验入口。","免费额度","https://www.mage.space/","Mage"],
["Craiyon","🖍️","图片","简单易用的文字生成图片工具。","免费入口","https://www.craiyon.com/","Craiyon"],
["Playground","🛝","图片 / 设计","AI 图像生成与编辑平台，提供免费使用额度。","免费额度","https://playground.com/","Playground"],
["Clipdrop","✂️","图片 / 设计","背景移除、清理、放大和生成等图像工具集合。","免费额度","https://clipdrop.co/","Stability AI"],
["Cleanup.pictures","🧽","图片","用 AI 删除照片中的人物、物体和瑕疵。","免费入口","https://cleanup.pictures/","Cleanup"],
["Remove.bg","🪄","图片 / 抠图","自动移除图片背景，适合证件照和商品图。","免费入口","https://www.remove.bg/","Canva"],
["OpusClip","🎞️","视频","把长视频自动切成适合短视频平台的片段。","免费额度","https://www.opus.pro/","OpusClip"],
["VEED","🎬","视频","在线 AI 视频编辑、字幕、配音和短视频制作。","免费入口","https://www.veed.io/","VEED"],
["InVideo AI","📹","视频","用文字快速生成视频脚本、素材和成片。","免费额度","https://invideo.io/","InVideo"],
["HeyGen","🧑‍💻","视频 / 数字人","AI 数字人、口播视频和多语言视频制作。","免费额度","https://www.heygen.com/","HeyGen"],
["TTSMaker","🔊","音频 / 配音","在线文字转语音工具，支持多语言和多种声音。","免费使用","https://ttsmaker.com/","TTSMaker"],
["PlayHT","🎙️","音频 / 配音","AI 语音生成与配音平台，提供免费体验额度。","免费额度","https://play.ht/","PlayHT"],
["AIVA","🎼","音乐","AI 作曲工具，可生成不同风格的音乐。","免费额度","https://www.aiva.ai/","AIVA"],
["Soundraw","🎹","音乐","AI 音乐生成与背景音乐创作工具。","免费试用","https://soundraw.io/","SOUNDRAW"],
["Tome","📖","演示 / 文档","AI 演示和故事化内容创作工具。","免费额度","https://tome.app/","Tome"],
["Beautiful.ai","✨","演示 / 文档","AI 辅助制作演示文稿和商务幻灯片。","免费试用","https://www.beautiful.ai/","Beautiful.ai"],
["Otter.ai","🦦","会议 / 音频","会议录音、转写、摘要和行动项整理工具。","免费额度","https://otter.ai/","Otter.ai"],
["Fireflies.ai","🔥","会议 / 音频","AI 会议记录、转写、摘要和搜索工具。","免费额度","https://fireflies.ai/","Fireflies.ai"],

["Jan","🖥️","本地 AI","开源桌面 AI 助手，可在本地运行模型。","免费 / 开源","https://jan.ai/","Jan"],
["GPT4All","🧠","本地 AI","桌面端本地运行和聊天的开源 AI 软件。","免费 / 开源","https://www.nomic.ai/gpt4all","Nomic"],
["ComfyUI","🧱","本地 AI","节点式开源生成式 AI 工作流工具。","免费 / 开源","https://www.comfy.org/","Comfy"],
["Fooocus","🖼️","本地 AI","面向新手的开源 Stable Diffusion 图像生成界面。","免费 / 开源","https://github.com/lllyasviel/Fooocus","Open Source"],
["Stable Diffusion","🌊","本地 AI","开放生态的图像生成模型，可本地运行。","免费 / 开源","https://stability.ai/stable-image","Stability AI"],
["CodeGeeX","💻","编程","中文友好的 AI 编程助手和代码生成工具。","免费入口","https://codegeex.cn/","Zhipu AI"],
["通义灵码","🪄","编程","阿里 AI 编程助手，提供 IDE 代码补全和问答。","免费使用","https://tongyi.aliyun.com/lingma","Alibaba"],
["Blackbox AI","🖤","编程","AI 编程助手，支持代码生成、解释与开发辅助。","免费额度","https://www.blackbox.ai/","Blackbox AI"],
["Replit","🧑‍💻","编程","在线编程环境，内置 AI 开发辅助功能。","免费入口","https://replit.com/","Replit"],
["Phind","🔎","编程 / 搜索","面向开发者的 AI 搜索与编程助手。","免费入口","https://www.phind.com/","Phind"],
["Symbolab","🧮","学习 / 研究","数学题求解与步骤讲解工具，适合学习。","免费入口","https://www.symbolab.com/","Symbolab"]
];
const cats=["全部",...new Set(tools.map(x=>x[2]))];let active="全部";
const $=s=>document.querySelector(s);
function renderCats(){ $("#cats").innerHTML=cats.map(c=>`<button class="cat ${c===active?"active":""}" data-c="${c}">${c}</button>`).join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{active=b.dataset.c;renderCats();render()})}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function normalize(s){return String(s||"").toLowerCase().replace(/[\\s_\\-]+/g,"").trim()}
function render(){const input=$("#search");const q=normalize(input.value);let a=tools.filter(x=>(active==="全部"||x[2]===active)&&(!q||normalize(x.join(" ")).includes(q)));if($("#sort").value==="name")a.sort((x,y)=>x[0].localeCompare(y[0]));if($("#sort").value==="free")a.sort((x,y)=>x[4].localeCompare(y[4]));$("#count").textContent=tools.length;$("#summary").textContent=`当前显示 ${a.length} 个`;$("#empty").hidden=a.length>0;$("#grid").innerHTML=a.map(x=>`<article class="card" data-name="${esc(x[0])}"><div class="top"><span class="icon">${x[1]}</span><span class="badge">${esc(x[4])}</span></div><h2>${esc(x[0])}</h2><div class="desc">${esc(x[3])}</div><div class="meta"><span class="tag">${esc(x[2])}</span><span class="tag">${esc(x[6])}</span></div><div class="card-actions guide-ready"><a class="open" href="${x[5]}" target="_blank" rel="noopener noreferrer">打开官网 ↗</a><a class="learn" href="tutorials/tool.html?tool=${encodeURIComponent(x[0])}">📖 这个工具怎么用？ / Guide</a></div></article>`).join("")}
function syncSearch(){const v=$("#search").value||"";if(v!==window.__lastSearchValue){window.__lastSearchValue=v;render()}}
["input","change","keyup","search","compositionend","blur","paste"].forEach(ev=>$("#search").addEventListener(ev,syncSearch));
setInterval(syncSearch,300);
$("#sort").onchange=render;renderCats();render();
function pickTask(task){const c=taskMap[task];if(c){active=c;renderCats();render()}$("#tools").scrollIntoView({behavior:"smooth",block:"start"})}
document.querySelectorAll(".starter-card").forEach(b=>b.onclick=()=>pickTask(b.dataset.task));
