// Search v2 configuration. Keep semantic knowledge here, not UI code.
const SearchConfig = {
  intents: [
    { id:"image", label:"图片创作", categories:["图片","设计"], phrases:["图片","图像","照片","画图","画画","绘图","绘画","做图","做图片","生成图片","图片生成","ai绘图","ai绘画","ai图片","海报","封面","头像","壁纸","插画","艺术图","概念图","商品图","产品图","商品照片","产品照片","抠图","去背景","背景移除","修图","图片编辑","image","images","photo","poster","illustration","art","design"] },
    { id:"video", label:"视频创作", categories:["视频","视频 / 音频"], phrases:["视频","做视频","生成视频","ai视频","视频生成","视频制作","短视频","短片","宣传片","口播","剪视频","剪辑","视频剪辑","字幕","视频字幕","视频特效","动画","video","videos","editing","shorts","reels"] },
    { id:"write", label:"写作办公", categories:["写作","写作 / 办公"], phrases:["写作","写文章","文章","作文","小说","写小说","故事","邮件","写邮件","文案","广告文案","改写","润色","扩写","缩写","报告","写报告","办公","写东西","writing","write","email","copywriting"] },
    { id:"learn", label:"学习研究", categories:["学习","学习 / 研究","搜索 / 研究"], phrases:["学习","学习资料","资料","查资料","研究","论文","查论文","文献","知识","学习笔记","做笔记","总结资料","读文档","看论文","数学题","作业","考试","学习英语","study","learn","research","paper","papers","math"] },
    { id:"code", label:"编程开发", categories:["编程","编程 / 开发","开发 / 模型"], phrases:["编程","代码","写代码","写程序","开发","程序","网站","做网站","网页","前端","后端","python","javascript","typescript","java","c++","程序报错","代码报错","debug","调试","coding","code","developer","development"] },
    { id:"chat", label:"聊天助手", categories:["聊天","聊天 / 综合","聊天 / 办公","聊天 / 助手"], phrases:["聊天","问问题","问答","助手","日常助手","头脑风暴","对话","陪伴","chat","assistant","brainstorm","conversation"] }
  ],
  tasks: [
    {id:"image_creation",intent:"image",label:"图片生成",phrases:["生成图片","图片生成","ai绘图","ai绘画","画图","绘图","做图片","做图","image generation","text to image"]},
    {id:"poster",intent:"image",label:"海报设计",phrases:["海报","宣传海报","封面","banner","poster","social post"]},
    {id:"avatar",intent:"image",label:"头像创作",phrases:["头像","人物头像","profile photo","avatar","headshot"]},
    {id:"product_image",intent:"image",label:"商品图片",phrases:["商品图","商品照片","产品图","产品照片","电商图片","淘宝图","商品宣传图","product photo","product image"]},
    {id:"background_remove",intent:"image",label:"抠图去背景",phrases:["抠图","去背景","背景移除","透明背景","remove background","background remover"]},
    {id:"video_creation",intent:"video",label:"视频生成",phrases:["生成视频","视频生成","ai视频","做视频","视频制作","短片","text to video"]},
    {id:"video_edit",intent:"video",label:"视频剪辑",phrases:["剪视频","剪辑","视频剪辑","视频编辑","edit video","video editing"]},
    {id:"short_video",intent:"video",label:"短视频",phrases:["短视频","short video","shorts","reels"]},
    {id:"subtitles",intent:"video",label:"字幕",phrases:["字幕","视频字幕","自动字幕","subtitle","subtitles","caption"]},
    {id:"digital_human",intent:"video",label:"数字人",phrases:["数字人","ai数字人","虚拟人","avatar video","talking avatar"]},
    {id:"article",intent:"write",label:"文章写作",phrases:["写文章","文章","作文","写博客","blog","article"]},
    {id:"copywriting",intent:"write",label:"文案",phrases:["文案","广告文案","营销文案","copywriting","marketing copy"]},
    {id:"email",intent:"write",label:"邮件",phrases:["写邮件","邮件","email"]},
    {id:"rewrite",intent:"write",label:"改写润色",phrases:["改写","润色","重写","rewrite","polish","improve writing"]},
    {id:"study_material",intent:"learn",label:"学习资料",phrases:["学习资料","学习笔记","总结资料","读文档","study notes","study material"]},
    {id:"paper_research",intent:"learn",label:"论文研究",phrases:["论文","查论文","文献","paper","papers","literature review"]},
    {id:"math",intent:"learn",label:"数学学习",phrases:["数学题","数学","math","equation"]},
    {id:"website",intent:"code",label:"做网站",phrases:["做网站","建网站","制作网站","网页","web app","website","web page"]},
    {id:"coding",intent:"code",label:"写代码",phrases:["写代码","写程序","coding","code","programming"]},
    {id:"debug",intent:"code",label:"调试代码",phrases:["debug","调试","程序报错","代码报错","修复bug","fix bug"]},
    {id:"python",intent:"code",label:"Python",phrases:["python","py"]},
    {id:"chat_general",intent:"chat",label:"通用聊天",phrases:["聊天","问问题","问答","助手","chat","assistant"]}
  ],
  stopPhrases:["我想要","我想","我要","我想用","我想让ai","我想让","我要用","帮我","请帮我","请问","有没有","能不能","可不可以","可以帮我","怎么用","怎么去","怎么才能","如何用","如何","怎样用","怎样","告诉我","教我","我需要","想要","想用","使用","用ai","用","一下","一个","一下子","给我","帮忙"],
  toolMeta:{
    "ChatGPT":{intents:["chat","learn","write","image","code"],tasks:["chat_general","article","study_material","image_creation","coding"],keywords:["问答","聊天","写作","图片","代码","学习"]},
    "Gemini":{intents:["chat","learn","write","image","code"],tasks:["chat_general","study_material","image_creation","coding"],keywords:["问答","研究","图片","代码","学习"]},
    "Claude":{intents:["chat","write","code","learn"],tasks:["article","rewrite","coding","study_material"],keywords:["长文","分析","写作","代码"]},
    "Perplexity":{intents:["learn"],tasks:["paper_research","study_material"],keywords:["搜索","研究","论文","资料"]},
    "NotebookLM":{intents:["learn"],tasks:["study_material","paper_research"],keywords:["资料","文档","笔记","研究","总结"]},
    "Leonardo AI":{intents:["image"],tasks:["image_creation","poster"],keywords:["图片","绘画","海报","插画"]},
    "Ideogram":{intents:["image"],tasks:["image_creation","poster"],keywords:["海报","文字排版","图片"]},
    "Adobe Firefly":{intents:["image"],tasks:["image_creation","poster"],keywords:["图片","设计","海报"]},
    "Canva":{intents:["image","write"],tasks:["poster","product_image","article"],keywords:["海报","设计","文案"]},
    "PhotoRoom":{intents:["image"],tasks:["product_image","background_remove"],keywords:["商品图","抠图","去背景"]},
    "Midjourney":{intents:["image"],tasks:["image_creation","poster"],keywords:["图片","绘画","概念图"]},
    "Krea":{intents:["image"],tasks:["image_creation"],keywords:["图片","设计","增强"]},
    "Recraft":{intents:["image"],tasks:["image_creation","poster"],keywords:["矢量","图标","品牌","海报"]},
    "Remove.bg":{intents:["image"],tasks:["background_remove"],keywords:["抠图","去背景"]},
    "Cleanup.pictures":{intents:["image"],tasks:["background_remove"],keywords:["图片编辑","去除物体"]},
    "Runway":{intents:["video","image"],tasks:["video_creation","video_edit"],keywords:["视频","生成","剪辑","特效"]},
    "Kling AI":{intents:["video"],tasks:["video_creation"],keywords:["视频","生成","运动控制"]},
    "Hailuo AI":{intents:["video"],tasks:["video_creation"],keywords:["视频","生成","短片"]},
    "Pika":{intents:["video"],tasks:["video_creation","short_video"],keywords:["视频","短视频","特效"]},
    "CapCut":{intents:["video"],tasks:["video_edit","subtitles","short_video"],keywords:["剪辑","字幕","短视频"]},
    "HeyGen":{intents:["video"],tasks:["digital_human","video_creation"],keywords:["数字人","口播","视频"]},
    "Synthesia":{intents:["video"],tasks:["digital_human","video_creation"],keywords:["数字人","培训视频"]},
    "Vizard":{intents:["video"],tasks:["video_edit","short_video","subtitles"],keywords:["剪辑","短视频","字幕"]},
    "OpusClip":{intents:["video"],tasks:["video_edit","short_video"],keywords:["长视频","短视频","剪辑"]},
    "Grammarly":{intents:["write"],tasks:["rewrite"],keywords:["英文","语法","润色","改写"]},
    "QuillBot":{intents:["write"],tasks:["rewrite"],keywords:["改写","总结","翻译"]},
    "Notion AI":{intents:["write","learn"],tasks:["article","study_material"],keywords:["写作","总结","知识库"]},
    "Jasper":{intents:["write"],tasks:["copywriting","article"],keywords:["营销","文案","内容"]},
    "Copy.ai":{intents:["write"],tasks:["copywriting"],keywords:["文案","营销","销售"]},
    "Writesonic":{intents:["write"],tasks:["article","copywriting"],keywords:["文章","SEO","内容"]},
    "Consensus":{intents:["learn"],tasks:["paper_research"],keywords:["论文","研究","证据"]},
    "Elicit":{intents:["learn"],tasks:["paper_research"],keywords:["论文","文献","研究"]},
    "Symbolab":{intents:["learn"],tasks:["math"],keywords:["数学","方程","题目"]},
    "WolframAlpha":{intents:["learn"],tasks:["math"],keywords:["数学","科学","计算"]},
    "GitHub Copilot":{intents:["code"],tasks:["coding","debug"],keywords:["代码","编程","IDE"]},
    "Gemini Code Assist":{intents:["code"],tasks:["coding","debug"],keywords:["代码","IDE","开发"]},
    "Cursor":{intents:["code"],tasks:["coding","debug","website"],keywords:["代码","编辑器","开发"]},
    "Replit":{intents:["code"],tasks:["coding","website"],keywords:["网站","代码","在线开发"]},
    "Bolt.new":{intents:["code"],tasks:["website","coding"],keywords:["网站","web app","开发"]},
    "Lovable":{intents:["code"],tasks:["website","coding"],keywords:["网站","web app","开发"]},
    "v0":{intents:["code"],tasks:["website"],keywords:["网页","UI","网站"]},
    "Cline":{intents:["code"],tasks:["coding","debug"],keywords:["代码","Agent","VS Code"]},
    "Roo Code":{intents:["code"],tasks:["coding","debug"],keywords:["代码","Agent","开发"]},
    "OpenHands":{intents:["code"],tasks:["coding","debug","website"],keywords:["代码","Agent","开发"]}
  }
};
window.ASHSearchConfig=SearchConfig;
